packages:
  - packages/**
  - .
  - e2e
  - apps/desktop/src/main

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - '@lobehub/editor'

overrides:
  '@lobehub/chat-plugin-sdk>swagger-client': 3.36.0
  '@swagger-api/apidom-reference': 1.1.0
  jose: ^6.1.3
  stylelint-config-clean-order: 7.0.0
  pdfjs-dist: 5.4.530
  # Package subpath './index.json' is not defined by "exports" in
  # https://github.com/niksy/css-functions-list/commit/1d222491e52339687e898d06cbb3989190cb94cb#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
  css-functions-list: 3.2.3

patchedDependencies:
  '@swagger-api/apidom-reference': patches/@swagger-api__apidom-reference.patch
  '@upstash/qstash': patches/@upstash__qstash.patch
