name: Sync to Mirrors
on:
  push:
    branches:
      - main
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Git committer
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ secrets.SAFE_EMAIL }}'
      - name: Sync to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          if [ -z "$GITLAB_TOKEN" ]; then echo "GITLAB_TOKEN not set, skipping."; exit 0; fi
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@gitlab.hk/${{ github.repository }}.git"
          git push --all gitlab && git push --tags gitlab && echo "✅ Synced to GitLab"
      - name: Sync to GitCode
        env:
          GITCODE_TOKEN: ${{ secrets.GITCODE_TOKEN }}
        run: |
          if [ -z "$GITCODE_TOKEN" ]; then echo "GITCODE_TOKEN not set, skipping."; exit 0; fi
          git remote add gitcode "https://${{ github.repository_owner }}:${GITCODE_TOKEN}@gitcode.com/${{ github.repository }}.git"
          git push --all gitcode && git push --tags gitcode && echo "✅ Synced to GitCode"